server.port=${PORT:8080}
server.forward-headers-strategy=framework
app.base-url=https://paradigmas6.agustingimenez.ar

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
