spring.application.name=shortener
spring.profiles.default=staging

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.link.ttl=60m
app.alias.length=5
app.alias.alphabet=23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz
