server.port=8080
app.base-url=http://localhost:8080

spring.datasource.url=jdbc:hsqldb:file:./data/shortener;shutdown=true
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
